select * from customer limit 20

--Q1.Total revenue generated by male and female customer?

select gender , sum(purchase_amount_usd)as revenu
from customer
group by gender 

--Q2.Which customer use discount but still spent more than the average purchase?

select customer_id,purchase_amount_usd
from customer
where discount_applied = 'Yes' and purchase_amount_usd >= (select AVG(purchase_amount_usd) from "Customer")

--Q3.which are the top 5 products which the highest average review rating?

select item_purchased,ROUND(AVG(review_rating::numeric)) as "Average Peoduct Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4.Compare the avarage Purchase Amounts between Standard and express shipping.

select shipping_type,
ROUND(AVG(purchase_amount_usd),2)
from customer
where Shipping_type in ('Standard','Express')
group by shipping_type

--Q5.Do subscribed customer spend more? 
--Compare average spend and total revenu between subscribers and non-subscribers.

select subscription_status,
COUNT(customer_id)as total_customer,
ROUND(AVG(purchase_amount_usd),2)as avg_spend,
ROUND(SUM(purchase_amount_usd),2)as total_revenue
from Customer
group by subscription_status
order by total_revenue,avg_spend desc;

--Q6.Which 5 product have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND( 100* SUM(CASE WHEN discount_applied ='Yes' THEN 1 ELSE 0 END)/COUNT(*),2)as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7.Segment customers into new, Returning,and Loyal based on their total 
--number of previous purchases,and show the count of each segment.

with customer_type as (
select customer_id, previous_purchases,
CASE
    WHEN previous_purchases =1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer 
)

Select customer_segment, count(*) as "Number of customers"
from customer_type 
group by customer_segment

--Q8.What are the top 3 most purchased product with in each category?

with item_counts as(
select category,
item_purchased,
COUNT (customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count (customer_id) DESC)as item_rank
from customer
group by category,item_purchased
)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <= 3;

--Q9.Are customer who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count (customer_id)as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--Q10.What is a revenue contribution of each age group?

select age_group,
SUM (purchase_amount_usd) as total_revenue
from customer
group by age_group
order by total_revenue desc;








